UKGovernmentBEIS/help-to-heat-GBIS

help_to_heat/templates/frontdoor/contact-details.html
Previously only showed Utility warehouse regardless of supplier selection
=> PC-377: Fix supplier showing up on the contact details page

help_to_heat/frontdoor/views.py
Adds session ID to responses. (Fun fact the session ID is generated on the homepage even though you can't see it yet)
=> PC-373: Add session id to response headers

help_to_heat/settings.py
Testing on prod, the session cookie already appears to have both HTTPOnly and Secure flags.
CSRF has HTTPOnly but was missing Secure, so have added that.
Leaving GA cookies alone, since HTTPOnly will prevent it working entirely and we still want analytics for users on HTTP.
=> PC-358 Cookie weaknesses

help_to_heat/settings.py, requirements-dev.lock, requirements-dev.txt, requirements.lock, requirements.txt
Added CSP middleware with explicit policies that match the pentest report suggestion, have verified both the presence of the header locally and that any other origins are blocked. From a cursory check (Ctrl-Shift-F `src=`) it looks like GTM is the only external source we use for anything.
Provided the Django setting to enable STS headers. Seems too painful to be worth testing locally, since we don't have valid SSL certs in local and Django tries to be clever about not setting them if a request didn't come in on HTTPS. It's possible it'll do the same when deployed, since HTTPS is terminated outside the application. If the header is missing, we'll either need the load balancer to set a header to indicate it *was* HTTPS, which we can tell Django to look for, or we don't bother with any of it …
=> PC-357 Security headers

help_to_heat/auth.py
The existing handling for errors is to set `username` to `None`. Returning `(None, None)` means we won't log the error, and set both `username` and `password` to `None`, which also feels conceptually sound in response to not having auth headers at all.
=> PC-382 suppress missing auth logging

help_to_heat/frontdoor/schemas.py
Initially missed off PR and has come up in QA, a change in copy was requested from 'Contact number' to 'Mobile number':
=> Pc 343 additional copy update

help_to_heat/frontdoor/views.py
This has been causing 500s because, if there is an error (eg a missing field) then the base class PageView is calling the super's get function with a data variable
=> PC-NONE: Add data=None to a few get methods

help_to_heat/frontdoor/interface.py
I don't know what's changed. I swear we previously didn't 500 if there were no addresses. I wonder if the OS API's changed?
=> PC-NONE: Addresses failing if none found

help_to_heat/settings.py
- Previously attempts to connect to Google Analytics (and thus send data) were blocked by the CSP security settings
- This change allows them to connect and send data
=> PC-NONE: Update CSP setting to allow google analytics connection

help_to_heat/templates/frontdoor/base.html, static/main.css
Added a custom class to set colour and font weight specifically, so user stylesheet on ios won't override it with white text colour.
Before
After
=> PC-none: Prevent user stylesheet overriding

help_to_heat/portal/download_views.py
Added "-" as a fallback in case of a key error/unanswered question for any of the multiple-choice questions, which will be shown in the CSV. The long form text question, if unanswered, just shows as "" in the CSV
=> PC-501: Handle unanswered multiple-choice questions on the feedback form to fix downloads

help_to_heat/frontdoor/views.py, tests/test_frontdoor.py
Removed British Gas from the unavailable suppliers list, but haven't removed the logic in case we'll need it in the future. If that's unlikely, I can amend the PR to remove it entirely @LadunOmideyiSoftwire
=> PC-559: Add BG back

help_to_heat/portal/download_views.py, tests/test_integration.py
Additions to the CSV requested by DESNZ, in particular:
- Country
- Postcode
- EPC letter rating (in the case where we don't find a rating, I've kept the original logic intact, so we will still populate "", instead of "Not found" - hopefully this is fine
What the CSV looks like now locally for me:
=> PC-519: CSV changes for service managers

help_to_heat/frontdoor/eligibility.py
remove logging eligibility as errors
=> PC-NONE: Remove logging from GBIS eligibility tests

help_to_heat/portal/download_views.py, help_to_heat/portal/urls.py, help_to_heat/portal/views.py, help_to_heat/templates/macros.html, help_to_heat/templates/portal/service-manager/supplier-list.html
closes PC-741
adds functionality to export data across a range
contains a new download_view endpoint for downloading a range
validation is done by the portal page to simplify error logic
the logic doesn't follow gov uk guidance exactly (a error precedence rule should be enforced meaning the three fields can't just be checked in series), for now this is omitted & all errors are displayed
=> PC-741 Download all referrals from a custom date range

.githooks/pre-commit, README.md
In the interests of preventing accidental commits of API keys. Simple hook that compares `web` and `web.template` in staged changes and rejects the commit if they don't match.
As discussed, longer-term goal is still getting the file gitignored.
=> PC-NONE: Add pre-commit hook

help_to_heat/frontdoor/views.py, tests/test_frontdoor.py
closes [PC-900](https://beisdigital.atlassian.net/browse/PC-900)
adds a back link exception in a similar style to [PC-898](https://github.com/UKGovernmentBEIS/help-to-heat-GBIS/pull/295), depending on the answer to the loft question
adds a verifying test, though it is quite large since it needs to nearly (but not quite) complete the whole flow. another option would be to utilise a flow finishing function & have the test press the back button twice
=> PC-900 Fix broken backlinks for Loft insulation

help_to_heat/frontdoor/views.py, tests/test_frontdoor.py
Added specific backlink cases to make the backlink on the following pages in the following scenarios route the user back to the /address page
From the benefits page when the following two conditions are fulfilled:
- The user selects that they have a Park Home
- There is no EPC found for their Park Home, or they've selected that they live in Scotland
From the property type page when the following two conditions are fulfilled:
- The user selects that they live in Social Housing
- There is no EPC found for their home, or they've selected that they live in Scotland
=> PC 898 partial fix specific backlinks

help_to_heat/frontdoor/views.py, tests/test_frontdoor.py
Added special cases to own-property backlinks where supplier is Bulb, Utility Warehouse, or Shell to go back to their appropriate warning page.
Added tests for these special cases too, to ensure they're working correctly.
=> PC-899: Fix backlinks for Special supplier warning pages (Shell, Bulb and Utility Warehouse)

help_to_heat/frontdoor/views.py, tests/test_frontdoor.py
closes [PC-971](https://beisdigital.atlassian.net/browse/PC-971)
the main issue is that the park home check took priority over the social housing check for deciding which flow the user is on. swapping the check fixes the issue of incorrect flow
also to fix the issue of the question appearing on the check answers page a new exception has been added to hide it when needed
added some tests to verify this. contains a few upgrades for tests
- functions to interface with the change buttons
- add a park home option when answering house questions
=> PC-971 Park homes questions incorrectly served when user changes answers from home owner to social housing

help_to_heat/frontdoor/schemas.py
closes [PC-1008](https://beisdigital.atlassian.net/browse/PC-1008)
follows a the same format as https://github.com/UKGovernmentBEIS/help-to-heat-GBIS/pull/270, where the supplier is removed only from frontdoor flow & not from the backend schema
=> PC-1008: Removing Ecotricity from the list of suppliers page

help_to_heat/frontdoor/views.py, tests/test_frontdoor.py
Change to prevent users changing (or even seeing) follow up questions regarding their loft, should they specify that they do not have one.
When the user answers yes: 
When the user answers no:
=> PC 994 prevent incompatible loft answers in change page

help_to_heat/middleware.py, help_to_heat/settings.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1135)
adds two new middleware:
- `ExceptionMiddleware`, which intercepts and reports errors
- `RequestLoggingMiddleware`, which logs all requests
will need to be merged to dev unfortunately to be able to test these changes
how much exactly will this cost? CloudWatch charges by the GB ingested, and is already costing ~£100 per month on current logging levels. is logging all requests going to be feasible?
can more be done with logging levels? CloudWatch doesn't appear to really have filtering for this, though it's possible to prepend ERROR or INFO to each request so the logs can be filtered
=> PC-1135: Improve error logging

help_to_heat/settings.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1194)
enables the request logging defined in [PC-1135](https://beisdigital.atlassian.net/browse/PC-1135)
adds a handler for internal django messaging. this should surface warnings such as CSRF fails
=> PC-1194 Further improve logging

help_to_heat/portal/download_views.py, help_to_heat/settings.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1218)
add a check before popping key
this resolves a KeyError if the key is not in the object, which can happen for invalid referrals
this does not fix the root issue, but does make the export handler more resilient
=> PC-1218: Fix key error if referral is missing PII

help_to_heat/frontdoor/views.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1221)
this will be further reviewed at a later date as part of [PC-1311](https://beisdigital.atlassian.net/browse/PC-1311)
=> PC-1221: add a failsafe for pressing back when it's not possible to send to summary

help_to_heat/frontdoor/interface.py, help_to_heat/frontdoor/views.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1291)
as part of the changes for the dump, we noticed on UAT the referrals were not surfacing. this is due to the routing not checking the database on the scotland flow. this should be resolved by this ticket
=> PC-1291: Fix Scottish EPC view

Makefile, README.md, docker/tests/check-code.sh, tests/docker-compose.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1415)
this ensures `black` and `isort` emit a non-zero exit code on formatting fail
`flake8` does this automatically so no changes needed here
job pre these changes: https://github.com/UKGovernmentBEIS/help-to-heat-GBIS/actions/runs/11611247770/job/32332179284
job post these changes: https://github.com/UKGovernmentBEIS/help-to-heat-GBIS/actions/runs/11611170314/job/32331954594
=> PC-1415: Fix pipelines not failing on code format fail

help_to_heat/frontdoor/views.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1349)
add a guard check for if there is no property type in the user's session
=> PC-1349: add a guard for if property type is not found

help_to_heat/frontdoor/interface.py, help_to_heat/frontdoor/views.py, help_to_heat/portal/download_views.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1374)
exposes the data in scottish epc to the csv
does this by saving an object similar to an E&W csv to the session
to think about; is this fine or should we have a more stringent schema? I wasn't able to add one easily as
- I'd like to keep the format consistent across E&W & scotland
- the E&W layout cannot easily be made into a marshmallow schema as many keys have hyphens. hyphens cannot be a field name in python
- we could make a new schema, but then the E&W data would need to change format & the csv exporter would need more cases to handle
=> PC-1374: Link new Scottish EPC database columns to Supplier CSV

help_to_heat/frontdoor/views.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1116)
querying `data` only queries answers on the current page. answers from other pages must be retrieved specifically.
have made comments surrounding this a bit clearer
=> PC-1116: Fix country check on address page

help_to_heat/frontdoor/schemas.py, help_to_heat/frontdoor/views.py, help_to_heat/locale/cy/LC_MESSAGES/django.po, tests/test_frontdoor.py, tests/utils.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1347)
adds a routing exception for the success page
in this case, the exception does nothing, so opted to mark it as `None`. could have a different way of marking that there's no previous page for `success`?
=> PC-1347: Routing error shown on success page

help_to_heat/frontdoor/schemas.py, help_to_heat/locale/cy/LC_MESSAGES/django.po
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1413)
Removed "I don't know" option from EPC question.
=> PC-1413: Remove "I don't know" option from EPC question

help_to_heat/frontdoor/mock_epc_api.py, help_to_heat/frontdoor/views.py, help_to_heat/locale/cy/LC_MESSAGES/django.po, tests/test_frontdoor.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1425)
adds a `.strip()` before passing off address and postcode to OS Places API
this should remove all kinds of whitespace
=> PC-1425: Fix for adding a space after address search first line can show no results

help_to_heat/frontdoor/schemas.py, help_to_heat/locale/cy/LC_MESSAGES/django.po
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1515)
add old copy to check_your_answers_options_map. this avoids a key not found error for old users
=> PC-1515: Fix for loft insulation error on check answers page

help_to_heat/settings.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1294)
use an explicit csrf origin. this should match the provided failing origin: `https://dev.check-eligibility-for-gb-insulation-scheme.service.gov.uk`
=> PC-1294: Fix CSRF Fail

help_to_heat/frontdoor/views.py, help_to_heat/locale/cy/LC_MESSAGES/django.po
Similar to how we have on WH:LG now, to get it off my to-do list
=> Redirect base URL to start page when running locally

help_to_heat/frontdoor/epc_api.py, help_to_heat/frontdoor/os_api.py, help_to_heat/utils.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1696)
adds timeouts to our two API calls in the projects.
went with 10 seconds as a reasonable amount of time to expect a user to wait
an example error we would expect to see is
```
[15/Jan/2025 12:06:07,473] [ERROR] An error occurred: HTTPSConnectionPool(host='epc.opendatacommunities.org', port=443): Read timed out. (read timeout=0.01)
2025-01-15T12:06:07.493417887Z Traceback (most recent call last):
2025-01-15T12:06:07.493426387Z   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
2025-01-15T12:06:07.493450989Z     self._validate_conn(conn)
2025-01-15T12:06:07.493453989Z   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in …
```
=> PC-1696: Handle unresponsive API

help_to_heat/settings.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1702)
as of 0.62.0 it's a separate package for social account support which we don't install https://docs.allauth.org/en/latest/release-notes/recent.html#id58
we don't use the social account (third party login integration) anyway
=> PC-1702: Remove unused allauth app

docker/web/Dockerfile
adds a user to the container dockerfile
this must appear after copying the app so the user can be given ownership of it
this must appear before the `collectstatic` line else the user won't own the result files
to flag, after this is merged it may be necessary to delete your 'staticfiles' folder locally. the start script will regenerate this with the correct permissions when next run
=> PC-1762: Switch to a non-root user in our container

docker/web/Dockerfile
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1851)
as we have switched to a non-root user we can no longer install it later on, so we must install at container build time
this is used often for accessing the database
=> PC-1851: Install psql in docker container

README.md
common issue with local dev on GBIS is the docker files being CRLF rather than LF
=> PC-NONE: Document approaches to line endings on the project
