- help_to_heat/portal/urls.py
- help_to_heat/portal/views.py
- help_to_heat/templates/portal/epc-page.html
> Frontend epc upload

- help_to_heat/templates/frontdoor/accessibility-statement.html
Removed redundant conditional and fixed indentation
> Feature pc 346 code tidy

- help_to_heat/frontdoor/schemas.py
> Pc 277 add subtext to walls question

- help_to_heat/frontdoor/views.py
- help_to_heat/templates/frontdoor/base.html
- help_to_heat/templates/frontdoor/privacy-policy.html
Made changes equivalent to the accessibility statement page, and tested that the same behaviour can be seen
> Pc 394 add back link to privacy policy page

- help_to_heat/templates/frontdoor/confirm-and-submit.html
> PC-343: Add to confirm and submit checkbox text

- help_to_heat/frontdoor/views.py
I have no idea if this is particularly "django-ic" but it seems fairly sensible to me
> PC-359: dont cache sensitive data

- envs/web
- help_to_heat/frontdoor/interface.py
- help_to_heat/frontdoor/views.py
- help_to_heat/portal/migrations/0012_scottishepcrating.py
- help_to_heat/portal/models.py
- help_to_heat/settings.py
This reverts commit afe73b6fcbfb5c19d2d759e66a2d18fe07459769.
> Revert "PC-43: Add logic for picking which table to use"

- docker/web/start.sh
single hotfix commit. Already on staging
> increase waitress threads 16 -> 64

- help_to_heat/templates/frontdoor/confirm-and-submit.html
I think this is enough, as simple as it looks
> Pc 408 anchor link

- .gitignore
- help_to_heat/frontdoor/eligibility.py
- help_to_heat/frontdoor/interface.py
- help_to_heat/frontdoor/views.py
- help_to_heat/portal/models.py
- tests/test_eligibility.py
- tests/test_frontdoor.py
- tests/test_interface.py
PC-NONE: Scottish EPC fix fr this time
> PC-NONE: various scotch epc fixes

- help_to_heat/frontdoor/interface.py
- help_to_heat/frontdoor/os_api.py
- help_to_heat/frontdoor/schemas.py
- help_to_heat/frontdoor/views.py
- help_to_heat/portal/models.py
- help_to_heat/templates/frontdoor/bulb-warning-page.html
- tests/test_frontdoor.py
- tests/test_interface.py
- tests/utils.py
https://beisdigital.atlassian.net/browse/PC-413
Supplier page - Bulb -> warning page -> contact details page
Bulb <-                        <- contact details page
- others -> contact details page
others <- contact details page
`Bulb, now part of Octopus Energy` will always be shown as the supplier except
- on success page
- in referral email
- in the actual referral
Tests have been fixed.
> Pc 413 bulb warning page

- help_to_heat/frontdoor/interface.py
- help_to_heat/frontdoor/schemas.py
- help_to_heat/frontdoor/views.py
- tests/test_eligibility.py
- tests/test_frontdoor.py
- tests/test_integration.py
https://beisdigital.atlassian.net/browse/PC-447
- Fix a bug along the way - before, if we go to supplier from summary page and select continue, we'll have to go through the whole journey again
> Pc 447 move supplier page

- help_to_heat/frontdoor/os_api.py
- help_to_heat/frontdoor/urls.py
- help_to_heat/frontdoor/views.py
- help_to_heat/templates/frontdoor/os-api-throttled.html
> PC-430: Add page shown if os api is throttled

- help_to_heat/templates/frontdoor/feedback-thanks.html
- Updates the feedback page text
- Adds a button for a user to return to their applications
-----
> PC-455: Update feedback thanks page

- docker/web/start.sh
- requirements.lock
- requirements.txt
Tidying up to do if this works, but want to verify ASAP.
> PC-NONE Swap Waitress server for Gunicorn

- static/robots.txt
> PC-431: Exclude portal

- help_to_heat/portal/views.py
- Removes Bulb from the suppliers shown on the portal supplier list
> PC-NONE: Hide bulb from portal supplier list

- help_to_heat/portal/views.py
> Pc-none: sort suppliers alphabetically

- help_to_heat/frontdoor/eligibility.py
- help_to_heat/frontdoor/schemas.py
- help_to_heat/frontdoor/views.py
- "Park home flow"
- Edit summary park to coop with new flow
Essentially duplicating the normal flow
> Pc 384 park home with logic

- help_to_heat/portal/download_views.py
- help_to_heat/portal/urls.py
- help_to_heat/templates/portal/service-manager/supplier-list.html
- tests/test_frontdoor.py
- Adds two buttons to the suppliers page
- One to download all referrals
- One to download referrals made in the last week
- They download in excel format
- They omit all customer PII
> PC-502: Allow service managers to download referrals

- help_to_heat/templates/frontdoor/base.html
- tests/test_frontdoor.py
https://beisdigital.atlassian.net/browse/PC-580
> PC-580: Change feedback form link and fix test

- help_to_heat/frontdoor/schemas.py
- help_to_heat/frontdoor/views.py
- help_to_heat/portal/download_views.py
- help_to_heat/portal/migrations/0013_add_referral_id.py
- help_to_heat/portal/models.py
- help_to_heat/portal/urls.py
- help_to_heat/templates/portal/service-manager/supplier-list.html
- tests/test_eligibility_scenarios.py
- tests/test_frontdoor.py
There are some formatting changes included here that aren't related to my changes but have appeared after running `make check-python-code`
> PC-708: Adjust weekly feedback download date range to one clear week

- help_to_heat/locale/cy/LC_MESSAGES/django.po
fixes some hanging translation changes
> PC-NONE: recompile translations

- requirements.lock
- requirements.txt
This PR simply updates eventlet in-place. Have tested the public site with `DEBUG=False` and all seems fine. Haven't tested the portal - I think there's some effort in setting up locally.
> PC-867: Update eventlet

- .github/pull_request_template.md
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1017)
this adds a pull request template, with additional check boxes for extracting translations & website flow
since this is not yet on main, I copied the template in manually to check it all looks fine
> PC-1017: Add PR template

- .github/workflows/main-label-check.yml
- .github/workflows/portal-checks.yml
Bringing github workflows into line across all our repos. Means everything should now run when we want it to.
n/a
> Fix GitHub workflow rules

- docker/web/start.sh
Adds a note to explain why what we're doing isn't ideal, but why we're doing it regardless, and refer to Jira ticket.
n/a
> PC-NONE: Add note about database migrations

- help_to_heat/frontdoor/urls.py
- help_to_heat/frontdoor/views.py
- help_to_heat/templates/frontdoor/error.html
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1135)
ticket to add an error causing endpoint.
**this ticket must be followed up by merging #324 before release, this is endpoint should not ever be available on staging or prod**
> PC-1135: add error causing endpoint

- .github/workflows/portal-checks.yml
- Makefile
- README.md
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1237)
see https://github.com/orgs/community/discussions/116610, `docker-compose` is now deprecated & can be replaced with `docker compose`
> PC-1237: update to docker compose v2

- help_to_heat/portal/views.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1238)
without it each referral is listed as a separate download, leading to way too many being returned
same fix as [PC-395](https://beisdigital.atlassian.net/browse/PC-395)
> PC-1238: Archive referral download created for each referral for Team Members

- README.md
- envs/tests
- envs/web.template
- help_to_heat/frontdoor/epc_api.py
- help_to_heat/settings.py
small update to change key to token to better reflect what the secret is
> PC-1295: Set up connection to open EPC API

- help_to_heat/frontdoor/interface.py
- help_to_heat/frontdoor/views.py
- help_to_heat/locale/cy/LC_MESSAGES/django.po
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1116)
account for None responses from the API gracefully.
> PC-1116: Fix for errors from search API

- .github/pull_request_template.md
> PC-NONE: add QA notes tick box to pull request template

- .github/dependabot.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1635)
Following the documentation & Sammy's work, this uses code similar to Sammy's FWTS code, but for poetry which uses "pip" in the YAML
ICS should have implemented the repo changes required for this following Sammy's FWTS request, but I haven't been able to check due to permissions.
> PC-1635: Add an automated package auditor

- help_to_heat/utils.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1804)
Small fix to month name for when users should check back for details about their Scottish EPC
> PC-1804: Scottish EPC month change

- help_to_heat/frontdoor/os_api.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1770)
this will help us identify any patterns in postcodes that are causing us ratelimit issues
> PC-1770: Add postcode to OS API logs

- help_to_heat/utils.py
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1822)
to reflect that we now have EPCs till january and we expect the next data dump to happen in may (so check back in june)
> PC-1822: Update Scottish EPC month names

- .github/dependabot.yml
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1702)
to be merged when we're finished, as we will no longer need daily scanning
> PC-1702: Decrease scan frequency to weekly

- docker/web/Dockerfile
duplicate of #478 
to be merged as part of [PC-1851](https://beisdigital.atlassian.net/browse/PC-1851)
> PC-1762: Switch to a non-root user in our container

- LICENCE
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1873)
updated years and attribute as recommended to GDS. also rename file to 'licence' as GDS recommends as well
https://gds-way.digital.cabinet-office.gov.uk/manuals/licensing.html
> PC-1873: Update copyright licence to include crown copyright

- help_to_heat/templates/macros.html
[Link to Jira ticket](https://beisdigital.atlassian.net/browse/PC-1867)
- changed destination for help for households link
> PC-1867: Change help for households link destination

- LICENCE
- help_to_heat/templates/macros.html
Merge PC-1867 into staging for client QA.
> Merge 'dev' -> 'staging'
